name: Build Anki Deck

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true
    - uses: actions/cache@v4.1.0
      with: 
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('deck_generator/*') }}
        path: |
          */target/
    - name: Run tests
      run: cd deck_generator && cargo test
    - name: Run anki card generation
      run: cd deck_generator && cargo build --release && ./target/release/deck_generator
    - uses: stefanzweifel/git-auto-commit-action@v4
        
